name: cav_gail
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - scipy>=1.10.0
  - pandas>=1.5.0
  - scikit-learn>=1.2.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - opencv-python>=4.8.0
    - pillow>=9.5.0
    - tqdm>=4.65.0
    - seaborn>=0.12.0
    - plotly>=5.15.0
    - gymnasium>=0.29.0
    - stable-baselines3>=2.0.0
